### ISSUE TITLE
doesnt have enough words

### ISSUE THREAD

**Issue by Samathingamajig** [B3nten/yggdrasil#1]
eggvidence

![image](https://user-images.githubusercontent.com/29130894/210485337-9d0823c4-1a40-4561-ba26-f246ef1f90bc.png)
![image](https://user-images.githubusercontent.com/29130894/210485352-db4282cc-d6dd-4822-9d30-b3552f94fb16.png)
![image](https://user-images.githubusercontent.com/29130894/210485366-2527dd0b-aae5-43b3-9d53-a56306b1af71.png)

**Comment by b3nten** [comment]
Fixed with [21c428b5bc0e351a668c014f4eafe612be47e3c9](https://github.com/B3nten/yggdrasil/commit/21c428b5bc0e351a668c014f4eafe612be47e3c9)
